# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    build: ./MariaDb
    restart: always
    environment:
      MYSQL_DATABASE: citsciclassify
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_USER_FILE: /run/secrets/mysql-user-name
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-user-password
    volumes:
      # change this in production
      - ./MariaDb/databasefiles:/var/lib/mysql:rw
      - ./MariaDb/schema.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3306:3306

  flask:
    build: ./Flask
    depends_on: 
      - db
    restart: always
    ports:
      - 9000:80